#!/usr/bin/env bash
set -euo pipefail

export PATH="/usr/local/bin:/usr/bin:/bin:${PATH:-}"

MATERIAL_PATH="${1:-${MATERIAL_PATH_ENV:-$HOME/.config/wallpaper/material.json}}"
QUICKCSS_PATH="${VESKTOP_QUICKCSS_PATH_ENV:-$HOME/.config/vesktop/settings/quickCss.css}"
SETTINGS_PATH="${VESKTOP_SETTINGS_PATH_ENV:-$HOME/.config/vesktop/settings/settings.json}"
QUICKCSS_PATHS=(
  "$QUICKCSS_PATH"
  "$HOME/.config/Vencord/settings/quickCss.css"
  "$HOME/.config/VencordData/settings/quickCss.css"
)

BEGIN_MARKER="/* BEGIN QUICKSHELL THEME SYNC */"
END_MARKER="/* END QUICKSHELL THEME SYNC */"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command not found: $1" >&2
    exit 127
  }
}

need_cmd jq
need_cmd python

if [[ ! -f "$MATERIAL_PATH" ]]; then
  echo "Material file not found: $MATERIAL_PATH" >&2
  exit 1
fi

use_dark=$(jq -r 'if (.is_dark_mode == true) or (.mode == "dark") then "true" else "false" end' "$MATERIAL_PATH")

pick_color() {
  local role="$1"
  local fallback="$2"
  if [[ "$use_dark" == "true" ]]; then
    jq -r --arg role "$role" --arg fallback "$fallback" '.colors[$role].dark // $fallback' "$MATERIAL_PATH"
  else
    jq -r --arg role "$role" --arg fallback "$fallback" '.colors[$role].light // $fallback' "$MATERIAL_PATH"
  fi
}

with_alpha() {
  local value="$1"
  local alpha="$2"
  if [[ "$value" =~ ^#[0-9a-fA-F]{6}$ ]]; then
    printf '#%s%s' "${value#\#}" "$alpha"
  else
    printf '%s' "$value"
  fi
}

important() {
  printf '%s !important' "$1"
}

background_primary=$(pick_color surface_dim "#1b1b1f")
background_secondary=$(pick_color surface_container_low "#1e1e22")
background_secondary_alt=$(pick_color surface_container "#222225")
background_tertiary=$(pick_color surface_container_high "#2a2a2e")
background_floating=$(pick_color surface_container_highest "$background_tertiary")
background_accent=$(pick_color surface_variant "#2b2b2f")

foreground=$(pick_color on_surface "#e3e3e7")
foreground_muted=$(pick_color on_surface_variant "#b5b5bb")
accent=$(pick_color primary "#8ab4f8")
accent_fg=$(pick_color on_primary "#0b0d12")
accent_container=$(pick_color primary_container "#2d3b55")
accent_container_fg=$(pick_color on_primary_container "#d7e3ff")
secondary=$(pick_color secondary "#a8c7fa")
tertiary=$(pick_color tertiary "#c58af9")
danger=$(pick_color error "#ff6b6b")
danger_fg=$(pick_color on_error "#ffffff")
outline=$(pick_color outline "#7f838a")
outline_variant=$(pick_color outline_variant "#6b6f76")

modifier_hover=$(with_alpha "$accent_container" "33")
modifier_active=$(with_alpha "$accent_container" "55")
modifier_selected=$(with_alpha "$accent_container" "66")
modifier_accent=$(with_alpha "$accent_container" "33")
mention_bg=$(with_alpha "$accent" "1f")
mention_hover=$(with_alpha "$accent" "33")
message_highlight=$(with_alpha "$accent" "14")
message_highlight_hover=$(with_alpha "$accent" "1f")
focus_ring=$(with_alpha "$accent" "66")
scrollbar_thumb=$(with_alpha "$outline_variant" "99")
scrollbar_track=$(with_alpha "$background_secondary" "33")

block=$(cat <<EOF
$BEGIN_MARKER
/* Autogenerated by quickshell theme sync. */
:root,
body,
#app-mount,
.theme-dark,
.theme-light {
  --background-primary: $(important "$background_primary");
  --background-secondary: $(important "$background_secondary");
  --background-secondary-alt: $(important "$background_secondary_alt");
  --background-tertiary: $(important "$background_tertiary");
  --background-accent: $(important "$background_accent");
  --background-floating: $(important "$background_floating");
  --background-modifier-hover: $(important "$modifier_hover");
  --background-modifier-active: $(important "$modifier_active");
  --background-modifier-selected: $(important "$modifier_selected");
  --background-modifier-accent: $(important "$modifier_accent");
  --background-mod-muted: $(important "$modifier_hover");
  --background-mentioned: $(important "$mention_bg");
  --background-mentioned-hover: $(important "$mention_hover");
  --background-message-hover: $(important "$modifier_hover");
  --background-message-highlight: $(important "$message_highlight");
  --background-message-highlight-hover: $(important "$message_highlight_hover");
  --deprecated-card-bg: $(important "$background_secondary_alt");
  --deprecated-card-editable-bg: $(important "$background_secondary_alt");
  --deprecated-store-bg: $(important "$background_primary");
  --deprecated-text-input-bg: $(important "$background_secondary_alt");
  --deprecated-text-input-border: $(important "$outline_variant");
  --deprecated-text-input-border-hover: $(important "$outline");
  --deprecated-text-input-border-disabled: $(important "$outline_variant");
  --deprecated-text-input-prefix: $(important "$foreground_muted");
  --modal-background: $(important "$background_secondary_alt");
  --modal-footer-background: $(important "$background_secondary");
  --app-background: $(important "$background_primary");
  --bg-overlay-1: $(important "$background_secondary");
  --bg-overlay-2: $(important "$background_secondary_alt");
  --bg-overlay-3: $(important "$background_tertiary");
  --bg-overlay-4: $(important "$background_floating");
  --bg-overlay-5: $(important "$background_accent");
  --bg-overlay-6: $(important "$background_accent");
  --background-base-lowest: $(important "$background_primary");
  --background-base-lower: $(important "$background_secondary");
  --background-base-low: $(important "$background_secondary_alt");
  --background-mod-subtle: $(important "$modifier_hover");
  --background-mod-normal: $(important "$modifier_active");
  --background-mod-strong: $(important "$modifier_selected");
  --message-background-hover: $(important "$modifier_hover");
  --card-background-default: $(important "$background_secondary_alt");

  --channeltextarea-background: $(important "$background_secondary_alt");
  --input-background-default: $(important "$background_secondary_alt");
  --input-border-default: $(important "$outline_variant");

  --text-normal: $(important "$foreground");
  --text-muted: $(important "$foreground_muted");
  --text-link: $(important "$accent");
  --text-positive: $(important "$secondary");
  --text-warning: $(important "$tertiary");
  --text-danger: $(important "$danger");
  --text-default: $(important "$foreground");
  --text-strong: $(important "$foreground");
  --text-muted: $(important "$foreground_muted");
  --text-link: $(important "$accent");
  --text-feedback-critical: $(important "$danger");
  --text-brand: $(important "$accent");
  --white: #ffffff;
  --white-500: #ffffff;

  --interactive-normal: $(important "$foreground_muted");
  --interactive-hover: $(important "$foreground");
  --interactive-active: $(important "$foreground");
  --interactive-muted: $(important "$outline_variant");
  --interactive-icon-default: $(important "$foreground_muted");
  --interactive-icon-hover: $(important "$foreground");
  --interactive-icon-active: $(important "$accent");
  --icon-muted: $(important "$foreground_muted");
  --icon-status-idle: $(important "$tertiary");
  --icon-status-dnd: $(important "$danger");
  --icon-status-offline: $(important "$outline_variant");

  --header-primary: $(important "$foreground");
  --header-secondary: $(important "$foreground_muted");
  --channels-default: $(important "$foreground_muted");
  --channel-icon: $(important "$foreground_muted");
  --embed-title: $(important "$accent");
  --border-subtle: $(important "$outline_variant");
  --border-muted: $(important "$outline_variant");
  --border-strong: $(important "$outline");
  --border-focus: $(important "$accent");
  --__adaptive-focus-ring-color: $(important "$focus_ring");
  --user-profile-border: $(important "$outline_variant");
  --user-profile-background-hover: $(important "$modifier_hover");

  --brand-experiment: $(important "$accent");
  --brand-experiment-560: $(important "$accent");
  --brand-experiment-500: $(important "$accent");
  --brand-experiment-600: $(important "$accent");
  --brand-experiment-400: $(important "$accent");
  --brand-experiment-330: $(important "$accent_container");
  --brand-experiment-300: $(important "$accent_container");

  --button-primary-background: $(important "$accent");
  --button-primary-background-hover: $(important "$accent");
  --button-primary-background-active: $(important "$accent");
  --button-primary-background-disabled: $(important "$accent_container");
  --button-secondary-background: $(important "$background_accent");
  --button-secondary-background-hover: $(important "$background_accent");
  --button-secondary-background-active: $(important "$background_accent");
  --button-secondary-background-disabled: $(important "$background_tertiary");
  --button-danger-background: $(important "$danger");
  --button-danger-background-hover: $(important "$danger");
  --button-danger-background-active: $(important "$danger");
  --button-danger-background-disabled: $(important "$danger");

  --control-primary-background-default: $(important "$accent");
  --control-primary-background-hover: $(important "$accent");
  --control-primary-border-default: $(important "$accent");
  --control-primary-border-hover: $(important "$accent");
  --control-primary-text-default: $(important "$accent_fg");
  --control-primary-text-hover: $(important "$accent_fg");
  --control-secondary-background-default: $(important "$background_accent");
  --control-secondary-background-hover: $(important "$background_tertiary");
  --control-secondary-border-default: $(important "$outline_variant");
  --control-secondary-border-hover: $(important "$outline");
  --control-secondary-text-default: $(important "$foreground");
  --control-secondary-text-hover: $(important "$foreground");
  --control-critical-primary-background-default: $(important "$danger");
  --control-critical-primary-background-hover: $(important "$danger");
  --control-critical-primary-border-default: $(important "$danger");
  --control-critical-primary-border-hover: $(important "$danger");
  --control-critical-primary-text-default: $(important "$danger_fg");
  --control-critical-primary-text-hover: $(important "$danger_fg");
  --control-critical-secondary-background-default: $(important "$danger");
  --control-critical-secondary-background-hover: $(important "$danger");
  --control-critical-secondary-border-default: $(important "$danger");
  --control-critical-secondary-border-hover: $(important "$danger");
  --control-critical-secondary-text-default: $(important "$danger_fg");
  --control-critical-secondary-text-hover: $(important "$danger_fg");
  --control-icon-only-background-hover: $(important "$modifier_hover");
  --control-icon-only-border-hover: $(important "$modifier_hover");
  --control-icon-only-icon-default: $(important "$foreground_muted");
  --control-icon-only-icon-hover: $(important "$foreground");
  --control-overlay-primary-background-default: $(important "$accent");
  --control-overlay-primary-background-hover: $(important "$accent");
  --control-overlay-primary-border-default: $(important "$accent");
  --control-overlay-primary-border-hover: $(important "$accent");
  --control-overlay-primary-text-default: $(important "$accent_fg");
  --control-overlay-primary-text-hover: $(important "$accent_fg");
  --redesign-button-secondary-background: $(important "$background_accent");
  --redesign-button-secondary-pressed-background: $(important "$background_tertiary");
  --redesign-button-danger-background: $(important "$danger");
  --redesign-button-positive-background: $(important "$secondary");
  --redesign-button-positive-pressed-background: $(important "$secondary");
  --brand-500: $(important "$accent");
  --primary-400: $(important "$accent");

  --scrollbar-thin-thumb: $(important "$scrollbar_thumb");
  --scrollbar-thin-track: $(important "$scrollbar_track");
  --scrollbar-auto-thumb: $(important "$scrollbar_thumb");
  --scrollbar-auto-track: $(important "$scrollbar_track");
  --scrollbar-auto-scrollbar-color-thumb: $(important "$scrollbar_thumb");
  --scrollbar-auto-scrollbar-color-track: $(important "$scrollbar_track");

  --status-positive: $(important "$secondary");
  --status-warning: $(important "$tertiary");
  --status-danger: $(important "$danger");
  --status-online: $(important "$secondary");
  --status-idle: $(important "$tertiary");
  --status-dnd: $(important "$danger");
  --status-offline: $(important "$outline_variant");
  --status-streaming: $(important "$accent");
  --badge-background-default: $(important "$accent");
  --color-online: $(important "$secondary");
  --color-total: $(important "$accent");
  --color-voice: $(important "$tertiary");
  --green-360: $(important "$secondary");
  --green-430: $(important "$secondary");
  --green-460: $(important "$secondary");
  --green-300: $(important "$secondary");
  --red-360: $(important "$danger");
  --red-460: $(important "$danger");
  --yellow-360: $(important "$tertiary");
  --spotify: $(important "$secondary");
  --primary-300: $(important "$accent");
  --primary-800: $(important "$accent");
  --bg: $(important "$background_primary");
  --fg: $(important "$foreground");
  --fg-secondary: $(important "$foreground_muted");
  --fg-semi-trans: $(important "$(with_alpha "$foreground" "99")");
  --link: $(important "$accent");
  --link-hover: $(important "$accent");
}

/* Chat input theming */
div[class*="chatContent"] form[class*="form"] {
  background-color: var(--background-secondary) !important;
  border-top: 1px solid var(--border-subtle) !important;
}

div[class*="channelTextArea"] {
  background-color: var(--background-secondary) !important;
}

div[class*="scrollableContainer"] {
  background-color: var(--channeltextarea-background) !important;
  border: 1px solid var(--border-subtle) !important;
}

div[class*="textArea"] {
  color: var(--text-normal) !important;
}

div[class*="placeholder"] {
  color: var(--text-muted) !important;
}
$END_MARKER
EOF
)

update_quickcss_file() {
  local path="$1"
  [[ -n "$path" ]] || return 0

  mkdir -p "$(dirname "$path")"
  touch "$path"

  local tmp_file="${path}.tmp"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { inblock = 1; next }
    $0 == end { inblock = 0; next }
    !inblock { print }
  ' "$path" > "$tmp_file"

  if [[ -s "$tmp_file" ]]; then
    printf '\n%s\n' "$block" >> "$tmp_file"
  else
    printf '%s\n' "$block" >> "$tmp_file"
  fi

  cat "$tmp_file" > "$path"
  rm -f "$tmp_file"
}

declare -A seen_paths
for path in "${QUICKCSS_PATHS[@]}"; do
  if [[ -n "${seen_paths[$path]:-}" ]]; then
    continue
  fi
  seen_paths["$path"]=1
  update_quickcss_file "$path"
done

if [[ -f "$SETTINGS_PATH" ]]; then
  python - "$SETTINGS_PATH" <<'PY'
import json
import sys
from pathlib import Path

settings_path = Path(sys.argv[1])
try:
    data = json.loads(settings_path.read_text())
except json.JSONDecodeError:
    print(f"Warning: failed to parse {settings_path}; skipping useQuickCss update.", file=sys.stderr)
    sys.exit(0)

if not isinstance(data, dict):
    data = {}

if data.get("useQuickCss") is not True:
    data["useQuickCss"] = True
    settings_path.write_text(json.dumps(data, indent=4, sort_keys=False) + "\n")
PY
fi

echo "Updated Vesktop QuickCSS: $QUICKCSS_PATH"
